from . import product_capacity
from . import product_warranty
from . import product_solarsystem
from . import product_estimated_annual_production
from . import product_battery_accessory1
from . import product_battery_accessory2
from . import product_installation_price
from . import product_template
from . import sale_order
from . import sale_order_line